---
- name: Disable Unnecessary System Services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "libvirtd.service"
    - "ModemManager.service"
    - "sshd.service"

- name: Enable Necessary System Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "dnscrypt-proxy.service"
